routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/ads', 'AdsController');
Auth::routes();

app/Ads.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Kyslik\ColumnSortable\Sortable;

class Ads extends Model
{
    use Sortable;

    protected $fillable = ['title', 'description', 'user'];

    public $sortable = [
        'created_at',
        'user',
        'title',
        ];

    public function user(){
        return $this->belongsTo('App\User', 'user', 'id');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function ads(){
        return $this->hasMany('App\Ads', 'user', 'id');
    }
}

app/Http/Controllers/AdsController.php
<?php

namespace App\Http\Controllers;

use App\Ads;
use App\User;
use Illuminate\Http\Request;
use App\Http\Requests\adsValidate;
use Illuminate\Support\Facades\Auth;

class AdsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $ads = Ads::sortable(['created_at' => 'desc'])->paginate(10);
        $users = User::all();
        return view('Ads.index', compact('ads', 'users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Ads.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(adsValidate $validate)
    {

        $parameters = $validate->all();
        $parameters['user'] = Auth::user()->id;

        Ads::create($parameters);

        return redirect('/ads');
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Ads  $ads
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $ad = Ads::find($id);
        if ($ad && Auth::user()->id == $ad->user) {
            return view('Ads.edit', compact('ad'));
        } else {
            return redirect('/ads');
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Ads  $ads
     * @return \Illuminate\Http\Response
     */
    public function update($id, adsValidate $validate)
    {

        Ads::whereId($id)->update($validate->except(['_method','_token']));

        return redirect('/ads');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Ads  $ads
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $ads)
    {
        $ads = Ads::find($ads->id);
        $ads->delete();
        return redirect('/ads')->with('success', 'You have deleted a post.');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = Auth::user();
        $ads = $user->ads;
        return view('home', compact('ads'));
    }


}

resources/views/Ads/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <h1>Create an Ad</h1>

        <a href="{{route('ads.index')}}" class="btn btn-primary float-right">Return</a>

        <div class="row">
            <div class="col-md-6 col-offset-3">

                @if($errors->all())
                    <div class="panel">
                        <ul class="alert-danger rounded">
                            @foreach($errors->all() as $error)
                                <li>{{$error}}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif

                <form action="{{route('ads.store')}}" method="POST">
                    <div class="form-group">
                        <label for="title">Title</label>
                        <input type="text" class="form-control" name="title">
                    </div>
                    <div class="form-group">
                        <label for="description">Description</label>
                        <textarea class="form-control" name="description"></textarea>
                    </div>

                    <button type="submit" class="btn btn-success btn-block">Submit</button>
                    @csrf
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/Ads/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <h1>Update an Ad</h1>

        <a href="{{route('ads.index')}}" class="btn btn-primary float-right">Return</a>

        <div class="row">
            <div class="col-md-6 col-offset-3">

                @if($errors->all())
                    <div class="panel">
                        <ul class="alert-danger rounded">
                            @foreach($errors->all() as $error)
                                <li>{{$error}}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif

                <form action="{{route('ads.update', $ad->id)}}" method="POST">
                    <div class="form-group">
                        <label for="title">Title</label>
                        <input type="text" class="form-control" name="title" value="{{$ad->title}}">
                    </div>
                    <div class="form-group">
                        <label for="description">Description</label>
                        <textarea class="form-control" name="description">{{$ad->description}}</textarea>
                    </div>

                    <button type="submit" class="btn btn-success btn-block">Submit</button>
                    @method("PUT")
                    @csrf
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/Ads/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <h1>Welcome to Ads page</h1>

        <div>
            @if(Session::has('success'))
                {{Session::get('success')}}
            @endif
        </div>

        <div class="row">
            @if (Auth::user())
            <a href="{{route('ads.create')}}" class="btn btn-primary m-1 right">Create</a>
            @endif
            <table class="table">
                <thead>
                    <tr>
                        <th>@sortablelink('created_at', 'Post date')</th>
                        <th>@sortablelink('title', 'Title')</th>
                        <th>@sortablelink('description', 'Description')</th>
                        <th>@sortablelink('user', 'User')</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($ads as $ad)
                        <tr>
                            <td>{{$ad->created_at}}</td>
                            <td>{{$ad->title}}</td>
                            <td>{{$ad->description}}</td>
                            <td>{{$users->find($ad->user)->name}}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <div>
                        @if(Session::has('success'))
                            {{Session::get('success')}}
                        @endif
                    </div>

                    <div class="row">

                        <a href="{{route('ads.create')}}" class="btn btn-primary m-1">Create</a>
                        <a href="{{route('ads.index')}}" class="btn btn-primary m-1 float-right">Return</a>
                        <table class="table sortable">
                            <thead>
                            <tr>
                                <th>@sortablelink('created_at', 'Post date')</th>
                                <th>@sortablelink('title', 'Title')</th>
                                <th>@sortablelink('description', 'Description')</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($ads as $ad)
                                <tr>
                                    <td>{{$ad->created_at}}</td>
                                    <td>{{$ad->title}}</td>
                                    <td>{{$ad->description}}</td>
                                    <td>
                                        <form action="{{route('ads.destroy', $ad)}}" method="POST">
                                            <a href="ads/{{$ad->id}}/edit" class="btn btn-warning btn-small">Edit</a>
                                            <button class="btn btn-danger btn-small" type="submit">Delete</button>
                                            <input type="hidden" name="id" value="{{$ad->id}}">
                                            @csrf
                                            @method("DELETE")
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel Ads page') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            <li class="nav-item">
                                @if (Route::has('register'))
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                @endif
                            </li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('home') }}">Home</a>
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>